name: Terraform Tests
on:
  pull_request
jobs:
  go-tests:
    name: Run Go Terraform Tests
    runs-on: ubuntu-latest
    steps:
      - uses: synapsestudios/run-terraform-test-suite@main
        with:
          go-version: 1.18.3
          terraform-version: 1.2.2
          fixtures-directory: "fixtures/terraform-aws-bastion-server"
          test-files-directory: test
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
