name: Terraform Tests
on:
  pull_request
  # push:
  #   branches:
  #     - main
jobs:
  # init:
  #   name: Initialize
  #   runs-on: ubuntu-latest
  #   outputs:
  #     messageTs: ${{ steps.notification.outputs.messageTs }}
  #   steps:
  #     - name: Initialize Slack Message
  #       id: notification
  #       uses: synapsestudios/build-status@v2
  #       with:
  #         type: "trigger"
  #         githubToken: ${{ secrets.GITHUB_TOKEN }}
  #         token: ${{ secrets.SYNOPS_SLACK_API_TOKEN }}
  #         channel: ${{ secrets.SLACK_CHANNEL_ID }}
  #         header: Build ${{ github.run_number }}
  go-tests:
    name: Run Go Terraform Tests
    runs-on: ubuntu-latest
    # needs: [init]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.2
      # - name: Set up notifications
      #   uses: synapsestudios/build-status@v2
      #   with:
      #     name: "Run Tests"
      #     messageTs: ${{ needs.init.outputs.messageTs }}
      #     jobStatus: ${{ job.status }}
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}
      #     token: ${{ secrets.SYNOPS_SLACK_API_TOKEN }}
      #     channel: ${{ secrets.SLACK_CHANNEL_ID }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Format Fixtures
        id: fmt-fixtures
        run: terraform fmt -check
        working-directory: fixtures/terraform-aws-bastion-server

      - name: Go Format
        id: gofmt
        run: gofmt -l .
        working-directory: test

      - name: Download Go Modules
        working-directory: test
        run: go mod download

      - name: Run Go Tests
        working-directory: test
        run: go test -v
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
