name: Terraform Tests
on:
  pull_request
jobs:
  go-tests:
    name: Run Go Terraform Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.18.3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.2
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Format Fixtures
        id: fmt-fixtures
        run: terraform fmt -check
        working-directory: fixtures/terraform-aws-bastion-server

      - name: Terraform Validate Fixtures
        id: validate-fixtures
        run: terraform validate
        working-directory: fixtures/terraform-aws-bastion-server

      - name: Go Format
        id: gofmt
        run: gofmt -l .
        working-directory: test

      - name: Download Go Modules
        working-directory: test
        run: go mod download

      - name: Run Go Tests
        working-directory: test
        run: go test -v
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
